server:
  port: 8070

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: lecture
          uri: http://localhost:8071/
          predicates: #조건절
            - Path=/lecture/**
          filters:
#            - AddRequestHeader=first-request, first-request-header2
#            - AddResponseHeader=first-response, first-response-header2
        - id: member
          uri: http://localhost:8072/
          predicates: #조건절
            - Path=/member/**
          filters:
#            - AddRequestHeader=second-request, second-request-header2
#            - AddResponseHeader=second-response, second-response-header2
        - id: board
          uri: http://localhost:8073/
          predicates: #조건절
            - Path=/board/**
          filters:
#            - AddRequestHeader=second-request, second-request-header2
#            - AddResponseHeader=second-response, second-response-header2