server:
  port: 8070

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: lecture-service
          uri: http://localhost:8071
          predicates: #조건절
            - Path=/lecture/**
          filters:
#            - AddRequestHeader=first-request, first-request-header2
#            - AddResponseHeader=first-response, first-response-header2
            - CustomFilter
        - id: member-service
          uri: http://localhost:8072
          predicates: #조건절
            - Path=/member/**
          filters:
#            - AddRequestHeader=second-request, second-request-header2
#            - AddResponseHeader=second-response, second-response-header2
            - CustomFilter
        - id: board-service
          uri: http://localhost:8073
          predicates: #조건절
            - Path=/board/**
          filters:
#            - AddRequestHeader=second-request, second-request-header2
#            - AddResponseHeader=second-response, second-response-header2
            - CustomFilter
        - id: info-service-service
          uri: http://localhost:8082
          predicates: #조건절
            - Path=/info-service/**
          filters:
            #            - AddRequestHeader=second-request, second-request-header2
            #            - AddResponseHeader=second-response, second-response-header2
            - CustomFilter
          default-filters:
            - name: GlobalFilter  #Global filter class 파일 명
              args: #파라미터로 전달될 값 정의
                message: hi global gateway
                preLogger: true
                postLogger: true
